# supabase/config.toml
project_id = "chat-app"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = []
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_in = false
minimum_password_length = 6

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false

[auth.sms]
enable_signup = false

[realtime]
enabled = true
max_mime_messages_per_second = 100

[storage]
enabled = true
file_size_limit = "50MiB"
